\documentclass{article}
\author{Carl Boettiger}
\title{An introduction to the \texttt{pmc} Package}
\usepackage{graphicx}
\usepackage{subfigure}
\usepackage[colorlinks]{hyperref}
\usepackage{amsmath}  % extended mathematics
\usepackage{booktabs} % book-quality tables
\usepackage{units}    % non-stacked fractions and better unit spacing
\usepackage{multicol} % multiple column layout facilities
\usepackage{lipsum}   % filler text
\usepackage{fancyvrb} % extended verbatim environments
\fvset{fontsize=\normalsize}% default font size for fancy-verbatim environments
\usepackage{xspace}
%-------------------------------------------------------------------------------
\RequirePackage{fancyvrb}
\RequirePackage{listings}
%% important: keep the following comment in
%% (see https://mailman.stat.ethz.ch/pipermail/r-help/2009-July/204747.html)
%% this comment persuades Sweav enot to insert\usepackage{Sweave}
%-------------------------------------------------------------------------------
\SweaveOpts{keep.source=TRUE}
%-------------------------------------------------------------------------------
<<SweaveListingsPreparations,results=tex,echo=FALSE,strip.white=false>>=
require(SweaveListingUtils)
## Must require any other packages to be loaded here
require(pmc)
SweaveListingPreparations()
##setToBeDefinedPkgs(....) line just necessary for the example;
## may be skipped in general
## you may also wish to pass arguments to SweaveListingPreparations()
## see ?SweaveListingPreparations 
setToBeDefinedPkgs(pkgs=c("SweaveListingUtils","distr", "pmc"),
                   keywordstyles=c("\\bf\\color{blue}","\\bf\\color{red}"))
@



\begin{document}
\maketitle
The Phylogentic Monte Carlo (\texttt{pmc}) package provides methods for estimating the power phylogenetic methods and providing a robust comparison of common phylogenetic models.  This package accompanies Boettiger \emph{et. al.} 2011, \emph{Is your phylogeny informative? Measuring the power of comparative methods.}  The following vignette is provided as the supplement to the paper.  


\section{Package availability}
The development version of the package is available on Github: \href{https://github.com/cboettig/pmc}{https://github.com/cboettig/pmc}, under Downloads.  The current source-code, issues tracking features, and version history are also available there.  A stable version will soon be submitted to the CRAN network.  


\section{Replicating the examples using demos}
This document uses Sweave to automatically regenerate the figures presented in the manuscript from the data provided. Each of the analyses presented in the paper is provided as a demo script in the package.  One can display all the demos, or call an individual demo, which displays and runs the code in the R console:

<<label=demos>>=
#demo(package="pmc")
#demo(geospiza_lambda)
@

The different demos create all the figures from the four different datasets analyzed in the paper (\emph{Geospiza}, simulated large tree, \emph{Anoles}, collection of simulated trees of varying sizes and shapes).  Some demos are run on a reduced number of replicates relative to the paper, but all demos may take some time to run on common personal computers.  Two additional scripts demonstrate other functionality of the package.  For more details on the available functions, consult the package help functions and package manual.  


\section{plots}
<<label=code1a, echo=FALSE>>=
data(geospiza_lambda) # option to use saved data from the manuscript
hist(bm_v_lambda$test_par_dist[3,], col=rgb(0,0,1,.5),
border="white", breaks=15, main="", xlab="Estimated lambda")
abline(v=lambda[[1]][3], lwd=3, lty=2, col="darkred") #True value
text(lambda[[1]][3], 300, "True lambda", pos=2)
@

<<label=code1b, echo=FALSE>>=
data(simtree_lambda_dist)
hist(bm_v_lambda$test_par_dist[3,], col=rgb(0,0,1,.5),
border="white", breaks=15, main="", xlab="Estimated lambda")
abline(v=lambda[[1]][3], lwd=3, lty=2, col="darkred") #True value
text(lambda[[1]][3], 300, "True lambda", pos=2)
@

<<label=code1c, echo=FALSE>>=
data(simtree_lambda_dist)
hist(bm_v_lambda$test_par_dist[2,], col=rgb(0,0,1,.5),
border="white", breaks=15, main="", xlab="Estimated sigma")
abline(v=lambda[[1]][2], lwd=3, lty=2, col="darkred") #True value
text(lambda[[1]][2], 300, "True sigma", pos=4)
@


\setkeys{Gin}{width=0.35\textwidth}
\begin{figure}
\begin{center}
\subfigure[]{
<<label=Fig1a, fig=TRUE, echo=FALSE>>=
<<code1a>> 
@
}\subfigure[]{
<<label=Fig1b, fig=TRUE, echo=FALSE>>=
<<code1b>> 
@
}\subfigure[]{
<<label=Fig1c, fig=TRUE, echo=FALSE>>=
<<code1c>> 
@
}
\end{center}
\caption{This example can be reproduced using \texttt{demo(geospiza\_lambda)} and \texttt{demo(simtree\_lambda\_dist)}}
\label{fig:one}
\end{figure}

<<label=Fig2a, fig=TRUE, echo=FALSE>>=
data(anoles_model_choice)
plot(ouLP_v_ouLP4, show_text=FALSE, test=FALSE, shade_p=TRUE, shade=FALSE)
@

<<label=Fig2b, fig=TRUE, echo=FALSE>>=
plot(ouLP_v_ouLP4, show_text=FALSE, shade_power=TRUE, shade=FALSE)
@

\setkeys{Gin}{width=0.5\textwidth}
  %% echo=TRUE won't work inside a subfigure environment
%\section{Figure 1}
%\begin{figure}
%\begin{center}
%\subfigure[]{ <<Fig2a>> }
%\subfigure[]{ <<Fig2b>> }
%\end{center}
%\caption{This example can be reproduced using \texttt{demo(anoles\_model\_choice)}}\label{fig:two}
%\end{figure}

\setkeys{Gin}{width=0.6\paperwidth}
<<label=code3, echo=FALSE>>=
data(anoles_model_choice)
layout(cbind(1,2,3,4), widths=c(1,1,1,1))
par(mar=c(5,.1,.1,.1))
plot(ouLP_tree, edge.color = treepalette(ouLP_tree), edge.width=5, show.tip.label=FALSE)
mtext("(a) OU.3", 1, cex=1.2)
plot(ouLP4_tree, edge.color = treepalette(ouLP4_tree), edge.width=5, show.tip.label=FALSE)
mtext("(b) OU.4", 1, cex=1.2)
plot(half_tree, edge.color = treepalette(half_tree), edge.width=5, show.tip.label=FALSE)
mtext("(c) OU.15", 1, cex=1.2)
plot(half_tree, edge.color ="white", edge.width=.1, cex=1., show.tip.label=TRUE, label.offset=-1.2)
@

% setting figure widths has to be done like this
\begin{figure}
\begin{center}
<<label=Fig3, fig=TRUE, echo=FALSE>>=
<<code3>>
@
\caption{This example can also be reproduced using \texttt{demo(anoles\_model\_choice)}}
\end{center}
\end{figure}



\setkeys{Gin}{width=0.8\textwidth}
<<label=code4, echo=FALSE>>=
data(anoles_model_choice)
par(mfrow=c(2,2))
plot(bm_v_ouLP, show_text=FALSE)
legend("topright", c("BM sims", "OU.3 sims", "obs"), pch=c(15,15,46),
lty=c(0,0,2), col=c(rgb(0,0,1,.5), rgb(1,0,0,.5), "darkred"), bty="n")

plot(ouLP_v_half, show_text=FALSE)
legend("topright", c("OU.3 sims", "OU.15 sims", "obs"), pch=c(15,15,46),
lty=c(0,0,2), col=c(rgb(0,0,1,.5), rgb(1,0,0,.5), "darkred"), bty="n")

plot(ouLP_v_ouLP4, show_text=FALSE)
legend("topright", c("OU.3 sims", "OU.4 sims", "obs"), pch=c(15,15,46),
lty=c(0,0,2), col=c(rgb(0,0,1,.5), rgb(1,0,0,.5), "darkred"), bty="n")

plot(bm_v_ou1, show_text=FALSE)
legend("topright", c("BM sims", "OU.1 sims", "obs"), pch=c(15,15,46),
lty=c(0,0,2), col=c(rgb(0,0,1,.5), rgb(1,0,0,.5), "darkred"), bty="n")
@


\setkeys{Gin}{width=0.8\textwidth}

\begin{figure}
\begin{center}
<<label=Fig4, fig=TRUE, echo=FALSE>>=
<<code4>>
@
\end{center}
\caption{This example can also be reproduced using \texttt{demo(anoles\_model\_choice)}}
\label{fig:four}
\end{figure}


\begin{figure}
\begin{center}
<<label=Fig5, fig=TRUE, echo=FALSE>>=
### Plots of the error rates ########
data(anoles_model_choice)
plot_error <- function(pow, null, test, info){
  plot(pow, shade_aic=T, shade=F, show_data=F, show_text=F, info=info, legend=TRUE, main=paste(null, "vs", test))
}
info <- "aic"
par(mfrow=c(2,2))
plot_error(bm_v_ouLP, "BM", "OU.3", info)
plot_error(bm_v_ou1, "BM", "OU.1", info)
plot_error(ouLP_v_ouLP4, "OU.3", "OU.4", info)
plot_error(ouLP_v_half, "OU.3", "OU.15", info)
@
\end{center}
\caption{This example can also be reproduced using \texttt{demo(anoles\_model\_choice)}}
\label{fig:five}
\end{figure}

\setkeys{Gin}{width=0.5\textwidth}
\begin{figure}
\begin{center}
<<label=Fig6a, fig=TRUE, echo=FALSE>>=
data("power_curves")
# n is a vec of number of taxa used in each sim: 
plot_size <- function(){
    k <- length(n)-2
  plot(1,1, type='n', xlim=c(min(alpha), max(alpha)), ylim = c(0,1),
       main="Power by tree size", log="x", xlab="alpha", ylab="power")
  for(i in 1:k ){ ## skip the last 2, which haven't converged
    points(alpha, size[[i]]$power, pch=16, col=i)
    lines(alpha, size[[i]]$power, col=i)
  }
  points(alpha, anoles$power, pch=16, col="purple")
  lines(alpha, anoles$power, col="purple", lwd=4)
  legend("topleft", c(paste(n[1:3], "taxa"), "23 (anoles)"), col=c(1:k,"purple"), pch=16  ) 

}
plot_size()
@
\end{center}
\caption{This example can be reproduced using \texttt{demo(power\_curves)}}
\label{fig:sixa}
\end{figure}



\begin{figure}
\begin{center}
<<label=Fig6b, fig=TRUE, echo=FALSE>>=
data("power_curves")
plot_shape <- function(){
  plot(1,1, type='n', xlim=c(min(alpha), max(alpha)), ylim = c(0,1),
  main="Power by tree topology", log="x", xlab="alpha", ylab="power")
    k <- length(lambda)
  for(i in 1:length(n)){
    points(alpha, shape[[i]]$power, pch=16, col=i)
    lines(alpha, shape[[i]]$power,  col=i)
  }
  points(alpha, anoles$power, pch=16, col="purple")
  lines(alpha, anoles$power, col="purple", lwd=4)
  legend("topleft", c(paste(lambda, "lambda"), "anoles"), col=c(1:k, "purple"), pch=16  ) 
}
plot_shape()
@
\end{center}
\caption{This example can also be reproduced using \texttt{demo(power\_curves)}}
\label{fig:sixb}
\end{figure}

\pagebreak




\section{Further examples}
From the output of the \texttt{montecarlotest} function, it is also possible to generate the distributions of the parameters.  For instance, this shows the distributions of the parameter outputs from the OU.3 model.  We also provide a function to calculate confidence intervals from these distributions.  It is further possible to create the distribution of parameter values observed under one model when simulating under the other, using \verb|out$test_sim_null_pars| or \verb|out$null_sim_test_pars|.  
\setkeys{Gin}{width=0.8\textwidth}

\begin{figure}
\begin{center}
<<label=parplot, fig=TRUE, echo=TRUE>>=
data(anoles_model_choice)
o <- confidenceIntervals.pow(bm_v_ouLP)
o[["test"]][,"sigma"]
plot_par_dists(bm_v_ouLP$test_par_dist)
@
\end{center}
\label{fig:S1}
\end{figure}



<<cleanup , echo=FALSE>>=
unloadNamespace("pmc")
unloadNamespace("SweaveListingUtils")
@


\end{document}


